## 1 Getting Started

### **1.1 Tensor**

In [57]:
# import libraries
import numpy as np
import torch

In [58]:
# Return an uninitilized matrix, does not contain definite known values
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00,  0.0000e+00, -5.7514e+06],
        [ 4.5898e-41, -1.4226e+07,  4.5898e-41],
        [ 1.7585e-13,  4.5900e-41, -1.4226e+07],
        [ 4.5898e-41,  1.3854e+26, -1.3127e+01],
        [-6.3689e+06,  4.5898e-41,  7.3156e+28]])


In [59]:
# Return randomly initialized matrix
x = torch.rand(5, 3)
print(x)

tensor([[0.2694, 0.0261, 0.9355],
        [0.5456, 0.8980, 0.3653],
        [0.1471, 0.9123, 0.7215],
        [0.5580, 0.1538, 0.9398],
        [0.2876, 0.2638, 0.7480]])


In [60]:
# Return a matrix filled with zeros, and define dtype
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [61]:
# Return matrix filled with zeros, and define dtype=short
x = torch.zeros(5, 3, dtype=torch.short)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int16)


In [62]:
# Return constructed tensor from data
x = torch.tensor([[5.5, 3, 4], [4, 5, 6]])
print(x)

tensor([[5.5000, 3.0000, 4.0000],
        [4.0000, 5.0000, 6.0000]])


In [63]:
# Return constructed tensor from data
# You can divide a tensor
normalization = 255
x = torch.tensor([1332, 2243, 1535])
print(x//normalization)

tensor([5, 8, 6])


In [64]:
# Return a new tensor based on an existing tensor.
# These methods will reuse properties of the input
# tensor unless specified otherwise
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [65]:
# Return with overrided dtype
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 2.2088,  0.8922,  1.0381],
        [ 0.2933,  1.0878, -1.2541],
        [ 0.0515,  0.6162,  1.4265],
        [-1.1953, -0.2922, -1.1169],
        [ 0.2200, -0.3021, -0.5953]])


In [66]:
# Return size
x.size()

torch.Size([5, 3])

### **1.2 Operations**

In [67]:
# Method1: Addition
y = torch.rand(5, 3)
print(x + y)

tensor([[ 2.2966,  1.1856,  1.8449],
        [ 0.6752,  1.6667, -0.5939],
        [ 0.6339,  0.7353,  2.2749],
        [-0.6333,  0.3441, -0.5223],
        [ 0.6299,  0.4787, -0.2027]])


In [68]:
# Method 2: Addition
print(torch.add(x, y))

tensor([[ 2.2966,  1.1856,  1.8449],
        [ 0.6752,  1.6667, -0.5939],
        [ 0.6339,  0.7353,  2.2749],
        [-0.6333,  0.3441, -0.5223],
        [ 0.6299,  0.4787, -0.2027]])


In [69]:
# Method 3: Addition
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 2.2966,  1.1856,  1.8449],
        [ 0.6752,  1.6667, -0.5939],
        [ 0.6339,  0.7353,  2.2749],
        [-0.6333,  0.3441, -0.5223],
        [ 0.6299,  0.4787, -0.2027]])


In [70]:
# Method 4: Addition (x to y)
y.add(x)
print(y)

tensor([[0.0878, 0.2935, 0.8068],
        [0.3819, 0.5790, 0.6602],
        [0.5824, 0.1191, 0.8484],
        [0.5620, 0.6364, 0.5946],
        [0.4099, 0.7808, 0.3927]])


In [71]:
# Return index (Like NumPy!)
print(x[:2])

tensor([[ 2.2088,  0.8922,  1.0381],
        [ 0.2933,  1.0878, -1.2541]])


In [72]:
# Return resized/reshaped tensor
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [73]:
# Return one element of tensor
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.1645])
-1.1644648313522339


### **NOTE: 100+ Operations on tensors**
+ [Link](https://pytorch.org/docs/stable/torch.html)

### **1.3 NumPy Bridge** 

In [74]:
# Convert Torch Tensor --> NumPy Array
a = torch.ones(5)
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [75]:
# Numpy array changed in value
a.add_(1)
print(a)

tensor([2., 2., 2., 2., 2.])


In [76]:
# Return NumPy Array with changed values
print(b)

[2. 2. 2. 2. 2.]


In [79]:
# Convert NumPy Array --> Torch Tensor
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [82]:
# # CUDA tensors
# If availible

# # let us run this cell only if CUDA is available
# # We will use ``torch.device`` objects to move tensors in and out of GPU
# if torch.cuda.is_available():
#     device = torch.device("cuda")          # a CUDA device object
#     y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
#     x = x.to(device)                       # or just use strings ``.to("cuda")``
#     z = x + y
#     print(z)
#     print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!# let us run this cell only if CUDA is available
# # We will use ``torch.device`` objects to move tensors in and out of GPU
# if torch.cuda.is_available():
#     device = torch.device("cuda")          # a CUDA device object
#     y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
#     x = x.to(device)                       # or just use strings ``.to("cuda")``
#     z = x + y
#     print(z)
#     print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!