## 1 Autigrad: Automatic Differentation

>Central to all neural networks in PyTorch is the `autograd` package. Let’s first briefly visit this, and we will then go to training our first neural network.

>The autograd package provides automatic differentiation for all operations on Tensors. It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.Central to all neural networks in PyTorch is the autograd package. Let’s first briefly visit this, and we will then go to training our first neural network.

>The autograd package provides automatic differentiation for all operations on Tensors. It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.

>If you set its attribute `.requires_grad` as `True`, it starts to track all operations on it. When you finish your computation you can call `.backward()` and have all the gradients computed automatically. The gradient for this tensor will be accumulated into .grad attribute.If you set its attribute .requires_grad as True, it starts to track all operations on it. When you finish your computation you can call .backward() and have all the gradients computed automatically. The gradient for this tensor will be accumulated into .grad attribute.

In [2]:
# import libraries
import torch

### **1.1 Tensors**

In [12]:
# Return a tensor and track computation
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [13]:
# Return tensor (addition)
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [14]:
# y was created as a result of an operation
print(y.grad_fn)

In [15]:
# More operations on y
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [20]:
# .requires_grad_( ... ) changes an existing Tensor’s requires_grad flag in-place. The input flag defaults to False if not given..requires_grad_( ... ) changes an existing Tensor’s requires_grad flag in-place. The input flag defaults to False if not given.
a = torch.randn(2, 2)
a = ((a*3) / (a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


### **1.2 Gradients**

In [22]:
# Let's backprop now.
out.backward()

In [23]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [25]:
## Example of vector-Jacobian product
x = torch.randn(3, requires_grad=True)
y = x*2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([  14.6049, -964.3001, -773.5444], grad_fn=<MulBackward0>)


In [26]:
# Now `y` is no longer a scalar
v = torch.tensor([0.1, 1.0, 0.00001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-03])


In [27]:
print(x.requires_grad)
print((x**2).requires_grad)
with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


In [28]:
# Use detach to get a new tensor with same content
print(x.requires_grad)
x = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
True
tensor(False)


### **NOTE**: Document about autograd.Function is at Document about autograd.
+ [link](https://pytorch.org/docs/stable/autograd.html#functionhttps://pytorch.org/docs/stable/autograd.html#function)